version: "3.8" 

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-arun}"
    image: cybulde-data-processing
    container_name: cybulde-data-processing-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/end-to-end-ml-419116-301079c6ad5a.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-arunkumar}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-arunkumar}/.config/gcloud
    ports:
      - 8888:8888
    ipc: host
    init: true